### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [nkeller1/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by damwhit** [comment]
@nkeller1 overall, good work on this. We do want you to make a couple of changes before we call you `technical ready`.

Please make the following edits:
Class 1 and class 1 object
* [x] change your `Menu` class to `Pizza`, since all attributes and methods seem unique to pizza, not a menu necessarily.
* [x] have a location attribute with a string value, instead of two integer values. How does that change your change location method? - make that update as well

 It is my understanding that a string can only have one assignment. Therefore I need to have a location value for the kitchen and the customer table. I set this up as an integer as there are many different locations the pizza could be (the oven, the prep table, the servers hand, etc.). As I understand the reasoning, it is no more or less work if each value is a string vs an integer, correct? If anyone is looking at the code it would be easier to interpret as a string. 

Class 2 and class 2 object:
* [x] make it so the addIce method changes an attribute - it looks like you have an appropriate one to change
* [x] what would be better data types for cupMaterial and lid based on your toGo method definition of ?

In think you mean string for cupMaterial and boolean for lid. I like cupMaterial as an array as there are only a few, limited, choices.  I've updated it with those changes but for future knowledge, why is string a better data type here? Thanks

  * [x] change those attributes to the more appropriate data types.

**Comment by damwhit** [comment]
@nkeller1 The beauty of OOP is that attributes can change in response to methods to reflect their current state. In the location attribute example, the following would make sense for an instance.
```
attribute
location: "kitchen"

method
serve_pizza: (changes location attribute from "kitchen" to "table")
```
Based on your class definition, locKitchen and locTable would be better suited as methods, that change a location attribute.

For the addIce method, I would expect an attribute of the drink to change.
ie.
```
attribute
is_cold: false

method
addIce: (changes is_cold attribute to true)
```

Arrays should only be used to store collections. In the case of a something like a cupMaterial, it's likely only one thing, so it should be a string. lid could be a boolean. That makes sense.
ie. 
```
cupMaterial: "plastic"
lid: false
```

**Comment by damwhit** [comment]
@nkeller1   We'd like you to create another class and example object file before we consider you `technical ready`

We want you to make a class_3 file and class_3_example_object file
Keep things simple. For this 3rd class and its example object: 
* [x] Only have 5 attributes and 4 methods 
* [x] Don't use any arrays or hashes
* [x] Make sure that your methods don't use any conditional logic and that they:
  * [x] have names that indicate actions
  * [x] change an attribute's value or return information pulled from an attribute(s).
